### ISSUE TITLE
can't find some entry in polkadotjs portal

### ISSUE THREAD

**Issue by alexxuyang** [JoshOrndorff/cumulus-workshop#1]
Just follow the workshop step by step, deploy a two node (polkadot's bkchr-cumulus-branch branch) local testnet with Alice & Bob, build the polkadotjs (master branch & most updated code) locally and start the frontend server, visit this server by: 
```
http://localhost:3000/#/?rpc=ws://IP_ADDRESS_OF_THE_SERVER:9944
```
And I found there are some entry missing in the protal, such like: chain states & extrinsics. Is there any version compatible issue between the node backend & frontend?

<img width="1440" alt="Screen Shot 2019-12-14 at 4 12 01 PM" src="https://user-images.githubusercontent.com/41315800/70845677-7a0abc00-1e8c-11ea-99a0-c8bd5f7a9bfd.png">

**Comment by JoshOrndorff** [comment]
Go back to the settings tab, and ensure you've selected "Fully featured" for interface operation mode.
![image](https://user-images.githubusercontent.com/2915325/70853189-a7e60580-1e78-11ea-99e5-3a50deb5e2dd.png) Click save, and (if necessary) refresh the page.

I'm 99% sure that's your issue, but if you still don't get the tabs to show up, please try the endpoint in that screenshot.

If you continue to have problems, please re-open. I'm happy to help.
